#!/bin/bash
# Thanks : Junegunn Choi
#
# Sungjin Kang(ujuc@ujuc.kr)
# 2014/10/19 ~

# RC files
cd $(dirname $BASE_SOURCE)
BASE=$(pwd)
touch bashrc-extra
for rc in *rc tmux.conf; do
    mkdir -pv bak
    [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
    ln -sv $BASE/$rc ~/.$rc
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
    curl https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# scripts
if [ $(uname -s) = 'Darwin' ]; then
    [ -z "$(which brew)" ] && ruby -e "$curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"

    brew install \
        ctags git tig vim tmux zsh macvim python python3
elif [ $(uname -s) = 'Linux' ]; then
    # Debian
    sudo apt-get install \
        build-essential curl git m4 ruby texinfo libbz2-dev \
        libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
    [ -z "$(which brew)" ] && ruby -e "$(wget -O- https://raw.github.com/Homebrew/linuxbrew/go/install)"
    brew install \
        ctags git tig vim tmux zsh python python3
else
    rm ~/.tmux.conf
    grep -v reattach-to-user-namespace tmux.conf > ~/.tmux.conf
fi

tmux source-file ~/.tmux.conf

./install-vim
