"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = false

[memory_usage]
disabled = false
threshold = -1
