command_timeout = 1000

[kubernetes]
disabled = false

[memory_usage]
disabled = false
threshold = -1

[status]
disabled = false

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[character]
error_symbol = "[λ](bold #ff5555)"
success_symbol = "[λ](bold #50fa7b)"
