# All SpaceVim option below [option] section
[options]
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"

  enable_guicolors = true

  buffer_index_type = 4
  automatic_update = true

[[custom_plugins]]
  repo = "junegunn/seoul256.vim"
  merged = 0

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "core#statusline"
  statusline_isparator = "bar"

[[layers]]
  name = "autocomplete"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"

[[lagers]]
  name = "debug"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"
  git_plugin = "fugitive"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#typescript"

[[custom_plugins]]
  name = 'github/copilot.vim'

